# Generated by Django 3.1.7 on 2021-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The unique title of the page displayed to the public.",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="The unique slug identifier used in URL addresses.",
                        max_length=255,
                        verbose_name="slug",
                    ),
                ),
                ("content", models.TextField()),
                ("revisions", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "db_table": "pages",
            },
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["-created_at"], name="pages_created_6eb0ef_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["-updated_at"], name="pages_updated_9b5c17_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["slug"], name="pages_slug_2ebe9d_idx"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(fields=("slug",), name="unique_slug"),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(fields=("title",), name="unique_title"),
        ),
    ]
